apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-diss.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pgw
  name: pgw
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgw
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-diss.yml
        kompose.version: 1.21.0 (992df58d8)
        k8s.v1.cni.cncf.io/networks: '[{
        "name": "macvlan-conf",
        "ips": [ "192.168.50.22" ],
        "default-route": ["192.168.50.1"]
        }]'

      creationTimestamp: null
      labels:
        io.kompose.network/physical: "true"
        io.kompose.service: pgw
    spec:
      containers:
      - command:
        - /bin/sh
        - /etc/open5gs/run_pgw.sh
        image: registry.local:5000/config-diss-upf_pgw:latest
        imagePullPolicy: "Always"
        name: open5gs-pgw
        resources: {}
        ports:
          - containerPort: 2123
            protocol: "UDP"
          - containerPort: 2152
            protocol: "UDP"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /etc/open5gs
          name: upf-cfg-claim0
      hostname: pgw
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: upf-cfg-claim0
        persistentVolumeClaim:
          claimName: upf-cfg-claim0
      dnsPolicy: None
      dnsConfig:
        nameservers: ["172.30.2.4"]
        searches:
        - local
