apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf
  labels:
    app.kubernetes.io/part-of: open5gs
data:
  bsf.yaml: |-
    db_uri: $MONGODB_URI
    logger:
        file: /var/log/open5gs/bsf.log

    parameter:

    bsf:
        sbi:
          - dev: eth0
            port: 7777
        
    nrf:
        sbi:
          - name: nrf
            port: 7777
