apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf
  labels:
    app.kubernetes.io/part-of: open5gs
data:
  nssf.yaml: |-

    logger:
        file: /var/log/open5gs/nssf.log

    parameter:

    nssf:
        sbi:
          - addr: 0.0.0.0
            port: 7777
        nsi:
          - name: nrf
            port: 7777
            s_nssai:
              sst: 1
    nrf:
        sbi:
          - name: nrf
            port: 7777
