db_uri: $MONGODB_URI


logger:
    file: /var/log/open5gs/udr.log

parameter:

udr:
    sbi:
      - addr: 172.30.1.14
        port: 7777

nrf:
    sbi:
      - addr:
          - 172.30.1.17
        port: 7777
